### ISSUE TITLE
consumer/producer ip of the same name/cg doesnt change

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#247]
**Describe the bug**
A certain station that already exists keep saving the old IP address of a certain producers/consumers which I used their names but from an entirely different host with a different IP address.

**To Reproduce**
1. Create a station
2. Connect a producer with name X
3. Disconnect the producer
4. Connect with the same producer name and same creds to the same station from a different host

**Expected behavior**
IP should be updated

**Comment by idanasulinmemphis** [comment]
Fixed in the latest release
