### ISSUE TITLE
Factory object removal

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#275]
## **Summary**
"Factory" object not making sense and adding a layer of complexity for no good reason.
Should be removed.

## **Context**
The initial thought was to add an extra level of management. After engaging with users, it turned out it's not being used in a way it makes sense for it to stay. 

## **Value**
Reduce complexity

## **Persona(s)**
- Data Engineers
- Developers

**Comment by idanasulinmemphis** [comment]
Released in the last version v0.3.6
