### ISSUE TITLE
Terraform for AWS

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#277]
## **Summary**
Create a terraform file to automatically deploy best practiced EKS with Memphis cluster 

## **Context**
Remove deployment frictions of Memphis Broker and have a faster, best-practiced deployment over the popular clouds

## **Value**
One-click installation of Memphis

## **Persona(s)**
- Data Engineers
- DevOps

**Comment by erankitcs** [comment]
I will be happy to work on this feature. I have already done some work on EKS using Terraform.
https://github.com/erankitcs/BookStoreAppOnEKS

**Comment by yanivbh1** [comment]
Hey @erankitcs,
That's great. The way we thought about doing it is by building a straightforward TF that spins up a 3-node EKS cluster of
t3.xlarge with public access and install Memphis cluster-mode on top.
What do you think?
@valeraBr feel free to join this discussion

**Comment by valeraBr** [comment]
Hi @erankitcs, so excited to see you here!
As @yanivbh1 mentioned we are looking for a super simple TF deployment to start with, if you want to share your knowledge with us it will be awesome.

**Comment by yanivbh1** [comment]
@erankitcs sounds great. Let's start small and steady with EKS.
Good idea about the dir tree

**Comment by valeraBr** [comment]
Hi @erankitcs,
Im thinking about open a slack channel for us. 
Its ok from your side?

**Comment by erankitcs** [comment]
Hey @valeraBr  Yes, that would be great.

**Comment by yanivbh1** [comment]
https://discord.gg/VmvaCQeUUj
@erankitcs @valeraBr

**Comment by idanasulinmemphis** [comment]
Released
