### ISSUE TITLE
Terraform for GCP

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#278]
## **Summary**
Create a terraform file to automatically deploy best practiced GKE with Memphis cluster 

## **Context**
Remove deployment frictions of Memphis Broker and have a faster, best-practiced deployment over the popular clouds

## **Value**
One-click installation of Memphis

## **Persona(s)**
- Data Engineers
- DevOps

**Comment by idanasulinmemphis** [comment]
Released
