### ISSUE TITLE
[DOCS] Updating the ReadMe File

### ISSUE THREAD

**Issue by krupalitrivedi** [memphisdev/memphis-broker#310]
I really appreciate the details present in the ReadMe file which gives a lot of details about the project to the people. It is important to see that many sentences in the ReadMe file need paraphrasing in order for them to make better sense. As well as there are a few formatting errors. We could simply start with the "Why" section of the ReadMe and then work ahead!

I would love to work on the same if you want!

**Comment by yanivbh1** [comment]
Hey @krupalitrivedi ,
Would be great to have your adjustments.

**Comment by yanivbh1** [comment]
Merged
