### ISSUE TITLE
Bug: problem in the logo of Memphis

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [memphisdev/memphis-broker#355]
### Describe the bug

The logo of memphis is not visible in the Readme as well as in the png file in white and dark mode.
Here is the screenshot : 

![image](https://user-images.githubusercontent.com/105960032/190892090-846dc85a-7efc-4429-800b-80980cd75bc8.png)

### Steps to reproduce

Go to [Dark Logo](https://github.com/memphisdev/memphis-broker/blob/master/logo-black.png) and [White Logo](https://github.com/memphisdev/memphis-broker/blob/master/logo-white.png) png files.

### Affected services

Other

### Platforms

Other

### If UI - Browsers

Other (add additional context)

### Additional context

Any browsers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by SaptarshiSarkar12** [comment]
@idanasulinmemphis Please look into this issue.

**Comment by yanivbh1** [comment]
Hey @SaptarshiSarkar12 , are you sure?
Looks good on my side.

**Comment by SaptarshiSarkar12** [comment]
@yanivbh1 can you post  a screenshot?

**Comment by yanivbh1** [comment]
![Uploading Screen Shot 2022-09-18 at 11.27.00.png…]()

**Comment by SaptarshiSarkar12** [comment]
ok @yanivbh1 . Then , it's a problem on my device. You can close this issue then.
