### ISSUE TITLE
Feature: get earliest broker logs for UI

### ISSUE THREAD

**Issue by OrMemphis** [memphisdev/memphis-broker#364]
### Current behavior

in standalone mode - the broker waits until it is possible to create a stream and then creates it and all logs from that point onwards are also published into the stream, so it's "fetchable" by the UI
in cluster mode (k8s) - the broker waits until there's a jetstream metadata leader until creating a stream and same as standalone.
we'd like to have all logs that were emitted since broker's start up available in the UI.

### Suggested solution

instead (or in addition) to publishing every emitted log directly to the stream, use a file log.
using NATS' file logger, we can then run in the background a fetch mechanism that pulls logs from the file and pushes them into our stream.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by idanasulinmemphis** [comment]
Has been released in v0.4.2
