### ISSUE TITLE
Bug: Create station with '.' not working

### ISSUE THREAD

**Issue by avrhamNeeman** [memphisdev/memphis-broker#365]
### Describe the bug

I tried to create a station with the name "aa.a" and received an error.
Also, the error was unclear
![Screen Shot 2022-09-19 at 15 40 30](https://user-images.githubusercontent.com/74565114/191028905-d0d970de-5096-4449-a850-f208f0b2f82e.png)

### Steps to reproduce

Create a new station with the character '.' as part of the station name

### Affected services

UI, SDKs

### Platforms

Other

### If UI - Browsers

Chrome

### Environment

Development

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by nirsht** [comment]
I think this is related to this issue https://github.com/memphisdev/memphis-broker/issues/246

**Comment by yanivbh1** [comment]
#246 is the feature request. It released in v0.3.6, and that's a bug on the fix
