### ISSUE TITLE
Feature: Consumer should be able to set their consume limit to any number more than 10

### ISSUE THREAD

**Issue by AmreeshTyagi** [memphisdev/memphis-broker#475]
### Current behavior

Currently, consumers are not able to consume more than 10 messages per request from server.

It is also visible on dashboard.

I believe, memphis consumer is using pull based consumer of NATS.

### Suggested solution

In few scenarios, consumers are supposed to consumed more than 10.
example: 
1. scenarios of basic check validation of message & pushing to some different queue to topic in existing infra, in that case my consumer can consume & process more than 10 messages. 
2. I would like save network request, so I would like to consume my process 100 messages in one go instead of 10 as my queue has million of messages.

Not sure, but this line logic seems preventing consumers to consume more than 10 messages.

https://github.com/memphisdev/memphis-broker/blob/480d7a4f31d192dca97a91f07d7eccf13d320411/server/memphis_helper.go#L284

```go
if consumer.MaxMsgDeliveries <= 0 || consumer.MaxMsgDeliveries > 10 {
		MaxMsgDeliveries = 10
	} else {
		MaxMsgDeliveries = consumer.MaxMsgDeliveries
	}
```

My suggestion is to use whatever value is coming from consumer configuration (more than 0)  to read messages, if possible. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Hi @AmreeshTyagi,
It is not correct.
That parameter defines the number of retires that the station will try to retransmit a message until it is marked as "poison" and automatically placed in a DLQ. Please refer to this section in the docs 
[](https://docs.memphis.dev/memphis/memphis/concepts/dead-letter-station-dlq)

There is no limitation to the number of messages a single consumer can consume.

**Comment by AmreeshTyagi** [comment]
Got it. Thanks. 

Just checked batchSize in consumer [parameters](https://docs.memphis.dev/memphis/memphis/concepts/consumer#parameters), which is giving flexibility to consume any batch size in single pull request. Missed it earlier. My bad.
