### ISSUE TITLE
Bug: Helm "analytics" flag unkown

### ISSUE THREAD

**Issue by Cave-Johnson** [memphisdev/memphis-broker#553]
### Describe the bug

The documentation states there is an `analytics` flag that can be set to false to "Collection of anonymous metadata" 
https://docs.memphis.dev/memphis/deployment/kubernetes/1-installation

When setting this to false Helm gives the error - `unknown flag`

### Steps to reproduce

```
helm install memphis memphis/memphis \
--analytics="false"
...
```

### Affected services

Broker

### Platforms

Kubernetes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
@valeraBr Please advice on this one. Thank you.

**Comment by valeraBr** [comment]
Hi @Cave-Johnson,

To use flags in deployment you must add **"--set"** before the flag. From the provided snippet looks like it's not there.

Thanks.

**Comment by Cave-Johnson** [comment]
Just to confirm it should look like
```
helm repo add memphis https://k8s.memphis.dev/charts/ --force-update
helm install memphis memphis/memphis \
  --create-namespace \
  --namespace memphis \
  --set cluster.enabled="true" \
  **--set analytics="false" \**
  --wait
```
