### ISSUE TITLE
Bug: HTTP Proxy health is shown as "Unhealthy" even due it is

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-broker#564]
### Describe the bug

HTTP Proxy health is shown as "Unhealthy" even due it is

### Steps to reproduce

Installation via docker-compose

### Affected services

UI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by idanasulinmemphis** [comment]
Fixed - will be released on the coming version 0.4.3
