### ISSUE TITLE
Bug: All "application" type users get the same connection token

### ISSUE THREAD

**Issue by Cave-Johnson** [memphisdev/memphis-broker#664]
### Describe the bug

Each user i create with type "application" receives the same identical connection token. This could present a security risk

Running version 0.4.3

### Steps to reproduce

in broker UI, create new user
select type = application
observe provided connection token

### Affected services

Broker

### Platforms

Kubernetes

### If UI - Browsers

Chrome

### Environment

Production, Development, Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Thanks for the report @Cave-Johnson .
We are aware of it, and it will be fixed in the coming release (0.4.4) as part of the new identity management.
