### ISSUE TITLE
Bug: Error in curl call on memphis.dev

### ISSUE THREAD

**Issue by wisbech** [memphisdev/memphis-broker#668]
### Describe the bug

I pasted the curl command from the mainpage [memphis.dev](memphis.dev) and got an error:

curl -s https://memphisdev.github.io/memphis-docker/docker-compose.yml -o docker-compose.yml && docker compose -f docker-compose.yml -p memphis up
> Error: unknown shorthand flag: 'f' in -f

I am on an os x machine and do not think this is the issue.

I corrected the call with an "-" in docker compose -> docker-compose to the following:
curl -s https://memphisdev.github.io/memphis-docker/docker-compose.yml -o docker-compose.yml && docker-compose -f docker-compose.yml -p memphis up

And now it works ;-)

### Steps to reproduce

1. Goto [memphis.dev](memphis.dev)
2. Click on "Copy" on the curl command
3. Paste in your terminal of choice
4. Get the "Error: unknown shorthand flag: 'f' in -f" in your prompt

### Affected services

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Weird, that's what I am receiving. Perhaps something in the terminal removing chars?
`curl -s https://memphisdev.github.io/memphis-docker/docker-compose.yml -o docker-compose.yml && docker compose -f docker-compose.yml -p memphis up`

**Comment by wisbech** [comment]
> 

> curl -s https://memphisdev.github.io/memphis-docker/docker-compose.yml -o docker-compose.yml && **docker compose** -f docker-compose.yml -p memphis up , is where the **issue** was for me. The curl string is straight from memphis.dev mainpage curl url

**Comment by valeraBr** [comment]
It may be a syntax issue. The syntax depends on the docker compose version as you can see from the official documentation.
If you want to use V1 you can alias "docker compose" to "docker-compose" on your local environment to solve the issue locally.

Can you please share with us your docker compose version?

**Comment by wisbech** [comment]
Of course I can.

> Docker Compose version v2.2.3

**Comment by valeraBr** [comment]
An update to the latest version may solve the issue, but I want to understand the cause of it for the future...
Do you have an alias for docker-compose command? Because it changed in V2 with the separate one, that's why it looks strange to me.

**Comment by wisbech** [comment]
> 

Sure thing - I just ran `alias` in my terminal  and it returned the following:

> docker=podman
> run-help=man
> which-command=whence

It might be the **docker=podman** creating issues with my system. 

Thank you @valeraBr for your help 👍
