### ISSUE TITLE
Bug: Using Official NATS server but changing release.

### ISSUE THREAD

**Issue by derekcollison** [memphisdev/memphis-broker#707]
### Describe the bug

This is wrong.

Keep the release that is stated in the files you are copying. Feel free to add your own as a secondary version but this is not only wrong it also makes it difficult to support and misleading to your users.

https://github.com/memphisdev/memphis-broker/blob/master/server/const.go#L43

### Steps to reproduce

https://github.com/memphisdev/memphis-broker/blob/master/server/const.go#L43

### Affected services

Broker

### Platforms

Other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by idanasulinmemphis** [comment]
Hi @derekcollison, thanks for bringing it into our attention. 

Could you please elaborate in what ways it can misleading the Memphis users?

**Comment by derekcollison** [comment]
You are full on running a NATS server but changing the version.

Best practice is to maintain the core version and then add additional versions as needed to denote your project's version.

**Comment by idanasulinmemphis** [comment]
Ok sounds reasonable, we will add it. 
Thanks again.
I'll close this issue once we will add it.

**Comment by idanasulinmemphis** [comment]
This has been added, closing this issue as completed
