### ISSUE TITLE
Feature: do not receive acknowledged messages option

### ISSUE THREAD

**Issue by 1k-off** [memphisdev/memphis-broker#719]
### Current behavior

When consumer app stops with calling Deregister() method, newly created consumers receives already acknowledged messages.

I mean, we crete new consumer with the next options (see code block) and scale it horizontally.
```
    client, err := conn.CreateConsumer(
        stationName,
        consumerName,
        memphis.ConsumerGroup(consumerGroup),
        memphis.ConsumerGenUniqueSuffix(),
    )
```
On successfully finished job Deregister() method called. 

When new job started, consumer starts receiving already acknowledged messages (actually, all messages from the station).

Current solutions:
- do not use ConsumerGenUniqueSuffix() option, so consumer has the same name after reconnect
- do not use Deregister() method, so memphis think, that consumer just inactive.

Both options causes problems with the autoscaling, because without first option there will be conflicts in names and too hard debugging process, and without the second option it's too hard to distinguish successfully stopped consumer app from crashed app.

Related discord thread: https://discord.com/channels/963333392844328961/1074408130345177149

### Suggested solution

The easiest and the proper way, I think, will to add `DoNotReceiveAlreadyAcknowledgedMessages()` option, or some like that. Possibly, make this behaviour default, so calling Deregister() method will not cause any problems.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by yanivbh1** [comment]
Thanks for the issue @1k-off .
@idanasulinmemphis @shay23b, can we please elaborate here?

**Comment by idanasulinmemphis** [comment]
Hi @1k-off, I believe that by saying "deregister" you mean "destroy".
In case this is the case so be aware that a consumer is actually a file containing the consumer offset inside the station. This is offset stored on a file for cases in which your application will be able to restart and start consuming again from where it stopped. When you are calling destroy that means that this consumer state is totally removed, hence you are getting the same messages again.
So destroy function is working as expected.
I'm wondering for what reason you are calling the destroy before shutting down your application. If you want the consumer to start consuming from the point it stopped you can skip destroying it

**Comment by 1k-off** [comment]
Hi, @idanasulinmemphis.
Yes, sorry. I mean "destroy".

So, what I'm talking about.
Let's imagine, that we have application worker (consumer) that can be scaled horizontally, for example, in k8s. And we have another application for producing data.

Every consumer calls `Destroy()` method on stop. It's correct behaviour. Every gorutine stops, and etc.
```
	stopCh := make(chan os.Signal)
	signal.Notify(stopCh, os.Interrupt, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-stopCh
		err = manager.Stop()
		if err != nil {
			log.Println(err)
			return
		}
		appService.Stop()
		os.Exit(255)
	}()
```
In the `manager.Stop()` we have a call to `consumer.Destroy()`. So, scaling down will gracefully stop some workers, and in the memphis UI I will see situation 1 from the screenshot.
https://i.imgur.com/0dOMDZW.png

And if we don't call `Destroy()` method then we will see situation 2 from the screenshot. But we'll the same situation if worker suddenly crashes (out of memory, nil pointer, etc). And we can't understand why consumer disconnected, was it planned or not?

So, let's return to the main question. If `Deregister()` called and there are no consumers right now in the station - new consumer will receive all messages from the station again (for example, after cluster restart, or re-deploy without additional batch). 
And if `Deregister() not called - we can't understand and evaluate application's behaviour.

Approach that you described, works for one consumer without scaling and without using `memphis.ConsumerGenUniqueSuffix()` option. Even if we don't plan to scale our application but use `memphis.ConsumerGenUniqueSuffix()` option - situation will be the same. Although in reality it makes little sense. It's just example.

**Comment by idanasulinmemphis** [comment]
Ok so you mean that you want something like consumer.close which will stop consuming but won't delete the consumer so that you will be able to see the consumer is ok in the UI?

**Comment by idanasulinmemphis** [comment]
Thanks for the detailed description.
The term acknowledged refers to a specific message-CG couple.
That's mean that if 1 CG has acknowledged the message and another CG don't, a specific message is acked for 1 CG but unacked to the other one.

Now in a scaled consumer with unique suffix case you have to create your consumer with the same consumer group - that way you will have the ability to create a new consumer on every application start and still to maintain the offset inside the station.
The suggestion to add a new consumer state is only for observability purpose in order you will have the ability to differentiate between crashed consumer to gracefully shut down consumers

**Comment by 1k-off** [comment]
Yes, in general. Thanks for the discussion and clarifying everything.
Because now I see that I was thinking rather one-sidedly suggesting the adding additional option for messages, although we can get the same by adding additional state for consumer.

**Comment by idanasulinmemphis** [comment]
Ok so I'm closing this one and please open a feature request for the new consumer function (.stop()/.close()).
Thanks
